version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENABLE_DOCKER_LOGS=${ENABLE_DOCKER_LOGS:-false}
    volumes:
      - ./temp_uploads:/app/temp_uploads
      - ./staticfiles:/app/staticfiles
      # Uncomment next line to enable Docker logs access (development only)
      # - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped 