# Generated by Django 5.2.1 on 2025-06-02 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enhanced_asset_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name'], 'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetsubtype',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Asset Subtype', 'verbose_name_plural': 'Asset Subtypes'},
        ),
        migrations.AlterModelOptions(
            name='severitymapping',
            options={'ordering': ['integration', 'external_severity']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.assettype'),
        ),
        migrations.AlterField(
            model_name='assetsubtype',
            name='cloud_provider',
            field=models.CharField(blank=True, help_text='AWS, Azure, GCP (for Cloud Resource category)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fieldmapping',
            name='target_field',
            field=models.CharField(help_text="Model field name (e.g., 'ip_address' or 'extra.os')", max_length=100),
        ),
        migrations.AlterField(
            model_name='severitymapping',
            name='internal_severity_level',
            field=models.SmallIntegerField(help_text='Normalised severity 0-10'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_group', models.ForeignKey(blank=True, help_text="User's default business group for data access", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessgroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
