# Generated by Django 5.2.1 on 2025-06-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_assetcategory_options_and_more'),
    ]

    operations = [
        # Rename vulnerability table to vulnerabilities (make it plural for consistency)
        migrations.AlterModelTable(
            name='vulnerability',
            table='vulnerabilities',
        ),
        
        # Rename scanner_integration table to integrations (more concise)
        migrations.AlterModelTable(
            name='scannerintegration',
            table='integrations',
        ),
        
        # Rename field_mapping table to integration_field_mappings (more descriptive)
        migrations.AlterModelTable(
            name='fieldmapping',
            table='integration_field_mappings',
        ),
    ]
