# Generated by Django 5.2.1 on 2025-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_table_naming_consistency'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerupload',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='scannerupload',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__isnull', False)), fields=('file_hash',), name='unique_file_hash'),
        ),
    ]
