# Generated by Django 5.2.1 on 2025-06-05 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_file_hash_duplicate_detection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('django', 'Django Application'), ('docker', 'Docker Container'), ('system', 'System'), ('nginx', 'Nginx')], db_index=True, max_length=50)),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_logs_timesta_789991_idx'), models.Index(fields=['level'], name='system_logs_level_245244_idx'), models.Index(fields=['source'], name='system_logs_source_3aba46_idx'), models.Index(fields=['user'], name='system_logs_user_id_85bc8b_idx'), models.Index(fields=['request_id'], name='system_logs_request_abf88a_idx')],
            },
        ),
    ]
